Dev
Romero10/api_training_project pull request #2
Opened 2021-12-23 16:23 UTC by Romero10

**Summary**: Response code is NOT 200 when getting a list of zip codes

**Preconditions**: I am authorized user.

**Steps:**
1. Send GET request to /zip-codes endpoint

**Actual Result**: Response code is 201.
**Expected Result**: Response code should be 200.

**Automation Test Coverage**
|| Test Class || Test Name ||
|  TC_ZipCode  |  availableZipCodesTest   |

--------------------------------------------------------------------------------
**Summary**: There are duplicates in available zip codes when adding a list of zip codes

**Preconditions**: I am authorized user.

**Steps**:
1. Send GET request to /zip-codes endpoint and select one of zip code
2. Send POST request to /zip-codes/expand endpoin with duplicate zip code (from step 1)
3. Send GET request to /zip-codes endpoint and make sure that no duplicate for zip code (from step 1)

**Actual Result**: There are duplicates in available zip codes.
**Expected Result**: There should be no duplicates in available zip codes.

**Automation Test Coverage**
|| Test Class || Test Name ||
|  TC_ZipCode  |  verifyAddDuplicationsZipCodesTest   |

--------------------------------------------------------------------------------
**Summary**: There are duplicates between available zip codes and already used zip codes

**Preconditions**: I am authorized user.

**Steps**:
1. Send GET request to /users endpoint and select one of zip code from any user
2. Send POST request to /zip-codes/expand endpoin with duplicate zip code (from step 1)
3. Send GET request to /zip-codes endpoint and make sure that zip code is NOT added (from step 1)

**Actual Result:** The already used zip code is added in available zip codes.
There are duplicates in available zip codes.
**Expected Result**: The already used zip code should NOT be added in available zip codes. 
There should be no duplicates in available zip codes (regarding to already used zip code).

**Automation Test Coverage**
|| Test Class || Test Name ||
|  TC_ZipCode  |  verifyAddDuplicationsUsedZipCodesTest   |

2021-12-24 11:09 UTC, EugenBorisik requested changes

2021-12-24 11:09 UTC, EugenBorisik commented on src/main/java/api/training/dto/UserDto.java
> +	@JsonProperty("age")
Optional: if json field name equals to java field name, then @JsonProperty annotation is not required

2021-12-24 11:09 UTC, EugenBorisik commented on src/main/java/api/training/services/UserService.java
> +		CloseableHttpResponse response = client.request(request);
You need to close responses

2021-12-24 11:09 UTC, EugenBorisik commented on src/test/java/TC_ZipCode.java
> +	private final static Sex SEX = Sex.MALE;
Generate random test data, do not use static values

2021-12-24 11:09 UTC, EugenBorisik commented on src/test/java/TC_ZipCode.java
> +					.get(RandomUtils.nextInt(0, availableZipCodes.second().size() - 1));
What if there is no available zip codes?

2021-12-24 11:09 UTC, EugenBorisik commented on src/test/java/TC_ZipCode.java
> +				"Zip Code '" + zipCode + "' are NOT added to available zip codes of application."));
Optional: I recommend to use String.format instead of + .. + ...

2021-12-25 22:52 UTC, Romero10 commented on src/main/java/api/training/services/UserService.java
> +		CloseableHttpResponse response = client.request(request);
Added the ability to close responses after requests

2021-12-25 22:52 UTC, Romero10 commented on src/test/java/TC_ZipCode.java
> +					.get(RandomUtils.nextInt(0, availableZipCodes.second().size() - 1));
Fixed.

2021-12-26 13:33 UTC, Romero10 commented on src/test/java/TC_ZipCode.java
> +	private final static Sex SEX = Sex.MALE;
Fixed.

2021-12-28 11:20 UTC, EugenBorisik approved these changes

2021-12-28 14:23 UTC, merged